using bams.server.Models.Transactions;

namespace bams.server.DTO.Transactions;

/// <summary>
/// One general-ledger line generated by a transaction.
/// </summary>
public sealed record TransactionAccountingEntryResponse(
    long Id,
    long GlAccountId,
    string GlAccountCode,
    string GlAccountName,
    long? CustomerAccountId,
    string? CustomerAccountNo,
    EntryType EntryType,
    decimal Amount,
    DateOnly PostingDate,
    string? Description,
    DateTime CreatedAt);