using bams.desktop.DTOs.Transactions;
using bams.desktop.Models;
using bams.desktop.Utils;
using bams.desktop.Commands;

namespace bams.desktop.ViewModels.Pages.Audit;

/// <summary>
/// One customer-account movement generated by the audited transaction.
/// Shows balances before and after the posting.
/// </summary>
public sealed record TransactionAuditAccountEntryDisplayModel(
    long AccountId,
    string AccountNo,
    string EntryTypeText,
    string AmountText,
    string LedgerBalanceBeforeText,
    string LedgerBalanceAfterText,
    string AvailableBalanceBeforeText,
    string AvailableBalanceAfterText,
    string ValueDateText,
    string PostingDateText,
    string DescriptionText,
    string ReferenceText)
{
    public static TransactionAuditAccountEntryDisplayModel FromResponse(
        AccountEntryResponse entry)
    {
        return new TransactionAuditAccountEntryDisplayModel(
            entry.AccountId,
            entry.AccountNo,
            entry.EntryType == EntryType.Debit ? "Debit" : "Credit",
            TransactionDisplay.FormatAmount(entry.Amount),
            TransactionDisplay.FormatAmount(entry.LedgerBalanceBefore),
            TransactionDisplay.FormatAmount(entry.LedgerBalanceAfter),
            TransactionDisplay.FormatAmount(entry.AvailableBalanceBefore),
            TransactionDisplay.FormatAmount(entry.AvailableBalanceAfter),
            entry.ValueDate.ToString(Constants.DisplayFormats.Date),
            entry.PostingDate.ToString(Constants.DisplayFormats.Date),
            TransactionDisplay.OrDash(entry.Description),
            TransactionDisplay.OrDash(entry.ReferenceNo));
    }
}

/// <summary>
/// One general-ledger line generated by the audited transaction.
/// </summary>
public sealed record TransactionAuditAccountingEntryDisplayModel(
    long Id,
    string GlAccountCode,
    string GlAccountName,
    string CustomerAccountText,
    EntryType EntryType,
    string EntryTypeText,
    string AmountText,
    string PostingDateText,
    string DescriptionText)
{
    public static TransactionAuditAccountingEntryDisplayModel FromResponse(
        TransactionAccountingEntryResponse entry)
    {
        return new TransactionAuditAccountingEntryDisplayModel(
            entry.Id,
            entry.GlAccountCode,
            entry.GlAccountName,
            TransactionDisplay.OrDash(entry.CustomerAccountNo),
            entry.EntryType,
            entry.EntryType == EntryType.Debit ? "Debit" : "Credit",
            TransactionDisplay.FormatAmount(entry.Amount),
            entry.PostingDate.ToString(Constants.DisplayFormats.Date),
            TransactionDisplay.OrDash(entry.Description));
    }
}

/// <summary>
/// One audit event associated with the transaction.
/// </summary>
public sealed record TransactionAuditLogDisplayModel(
    long Id,
    string UserText,
    string Action,
    string DetailsText,
    string IpAddressText,
    string DeviceInfoText,
    string CreatedAtText)
{
    public static TransactionAuditLogDisplayModel FromResponse(
        TransactionAuditLogResponse log)
    {
        var userText = !string.IsNullOrWhiteSpace(log.FullName)
            ? log.FullName
            : $"User #{log.UserId}";

        return new TransactionAuditLogDisplayModel(
            log.Id,
            userText,
            log.Action,
            TransactionDisplay.OrDash(log.Details),
            TransactionDisplay.OrDash(log.IpAddress),
            TransactionDisplay.OrDash(log.DeviceInfo),
            TransactionDisplay.FormatTimestamp(log.CreatedAt));
    }
}

/// <summary>
/// Read-only presentation of one transaction for auditor investigation.
/// Contains lifecycle, customer-account movements, GL entries, transfer-specific
/// detail, reversal information and transaction audit events.
/// </summary>
public sealed class TransactionAuditDetailViewModel : ViewModelBase
{
    public event Action? BackRequested;
    public RelayCommand BackCommand { get; }
    public TransactionAuditDetailViewModel(
        TransactionDetailResponse transaction)
    {
        Transaction = transaction;
        BackCommand = new RelayCommand(_ => BackRequested?.Invoke());

        AccountEntries = transaction.AccountEntries
            .Select(TransactionAuditAccountEntryDisplayModel.FromResponse)
            .ToList();

        AccountingEntries = transaction.AccountingEntries
            .Select(TransactionAuditAccountingEntryDisplayModel.FromResponse)
            .ToList();

        AuditLogs = transaction.AuditLogs
            .Select(TransactionAuditLogDisplayModel.FromResponse)
            .ToList();

        TotalDebit = transaction.AccountingEntries
            .Where(entry => entry.EntryType == EntryType.Debit)
            .Sum(entry => entry.Amount);

        TotalCredit = transaction.AccountingEntries
            .Where(entry => entry.EntryType == EntryType.Credit)
            .Sum(entry => entry.Amount);
    }

    public TransactionDetailResponse Transaction { get; }

    public IReadOnlyList<TransactionAuditAccountEntryDisplayModel> AccountEntries { get; }

    public IReadOnlyList<TransactionAuditAccountingEntryDisplayModel> AccountingEntries { get; }

    public IReadOnlyList<TransactionAuditLogDisplayModel> AuditLogs { get; }

    // ===== General transaction information =====

    public string TransactionNo => Transaction.TransactionNo;

    public string TypeText =>
        TransactionDisplay.ToDisplayName(Transaction.TransactionType);

    public TransactionStatus Status => Transaction.TransactionStatus;

    public string StatusText =>
        TransactionDisplay.ToDisplayName(Status);

    public string AmountText =>
        TransactionDisplay.FormatMoney(Transaction.Amount);

    public string FeeAmountText =>
        TransactionDisplay.FormatMoney(Transaction.FeeAmount);

    public string ReferenceText =>
        TransactionDisplay.OrDash(Transaction.ReferenceNo);

    public string DescriptionText =>
        TransactionDisplay.OrDash(Transaction.Description);

    public string TransactionAtText =>
        TransactionDisplay.FormatTimestamp(Transaction.TransactionAt);

    public string CreatedAtText =>
        TransactionDisplay.FormatTimestamp(Transaction.CreatedAt);

    public string UpdatedAtText =>
        TransactionDisplay.FormatTimestamp(Transaction.UpdatedAt);

    // ===== Lifecycle =====

    public string InitiatedByText =>
        FormatUser(
            Transaction.InitiatedBy,
            Transaction.InitiatedByUsername,
            Transaction.InitiatedByFullName);

    public string AuthorizedByText =>
        Transaction.AuthorizedBy is null
            ? "—"
            : FormatUser(
                Transaction.AuthorizedBy.Value,
                Transaction.AuthorizedByUsername,
                Transaction.AuthorizedByFullName);

    public string AuthorizedAtText =>
        TransactionDisplay.FormatTimestamp(Transaction.AuthorizedAt);

    public string PostedByText =>
        Transaction.PostedBy is null
            ? "—"
            : FormatUser(
                Transaction.PostedBy.Value,
                Transaction.PostedByUsername,
                Transaction.PostedByFullName);

    public string PostedAtText =>
        TransactionDisplay.FormatTimestamp(Transaction.PostedAt);

    // ===== Reversal =====

    public bool HasReversalRelationship =>
        Transaction.ReversalOfTransactionId is not null;

    public string ReversalOfText =>
        Transaction.ReversalOfTransactionId is { } reversedId
            ? $"Transaction #{reversedId}"
            : "—";

    // ===== Customer-account movements =====

    public bool HasAccountEntries => AccountEntries.Count > 0;

    // ===== Accounting / GL postings =====

    public bool HasAccountingEntries => AccountingEntries.Count > 0;

    public decimal TotalDebit { get; }

    public decimal TotalCredit { get; }

    public decimal AccountingDifference =>
        Math.Abs(TotalDebit - TotalCredit);

    public string TotalDebitText =>
        TransactionDisplay.FormatAmount(TotalDebit);

    public string TotalCreditText =>
        TransactionDisplay.FormatAmount(TotalCredit);

    public string AccountingDifferenceText =>
        TransactionDisplay.FormatAmount(AccountingDifference);

    /// <summary>
    /// True when at least one accounting entry exists and total debits equal total credits.
    /// </summary>
    public bool IsAccountingBalanced =>
        HasAccountingEntries && TotalDebit == TotalCredit;

    public bool HasAccountingMismatch =>
        HasAccountingEntries && !IsAccountingBalanced;

    public bool HasMissingAccountingEntries =>
        !HasAccountingEntries;

    public string AccountingStatusText =>
        HasMissingAccountingEntries
            ? "Missing entries"
            : IsAccountingBalanced
                ? "Balanced"
                : "Mismatch";

    // ===== Audit trail =====

    public bool HasAuditLogs => AuditLogs.Count > 0;

    // ===== NRC transfer =====

    public bool HasNrcTransfer =>
        Transaction.NrcTransfer is not null;

    public string SenderText =>
        Transaction.NrcTransfer is { } nrc
            ? $"{nrc.SenderName} · {nrc.SenderNrc}{PhoneSuffix(nrc.SenderPhone)}"
            : string.Empty;

    public string ReceiverText =>
        Transaction.NrcTransfer is { } nrc
            ? $"{nrc.ReceiverName} · {nrc.ReceiverNrc}{PhoneSuffix(nrc.ReceiverPhone)}"
            : string.Empty;

    public string PickupLocationText =>
        Transaction.NrcTransfer is { } nrc
            ? nrc.DeliveryType == Constants.TransactionFieldRules.NrcDeliveryAtOtherBank
                ? $"{nrc.PickupLocation} (another bank)"
                : nrc.PickupLocation
            : string.Empty;

    public string PaymentText =>
        Transaction.NrcTransfer is { } nrc
            ? (nrc.IsPaidInCash
                ? "Sender paid in cash"
                : "Sender paid from their account")
              + (nrc.PickedUpAt is null
                  ? string.Empty
                  : nrc.DestinationAccountId is null
                      ? " · paid out in cash"
                      : " · paid into the receiver's account")
            : string.Empty;

    public string PickupText
    {
        get
        {
            if (Transaction.NrcTransfer is not { } nrc)
            {
                return string.Empty;
            }

            var state = nrc.PickedUpAt is not null
                ? $"Paid out {TransactionDisplay.FormatTimestamp(nrc.PickedUpAt)}"
                : Status == TransactionStatus.Pending
                    ? $"Waiting for pickup until {TransactionDisplay.FormatTimestamp(nrc.PickupExpiresAt)}"
                    : "Cancelled, sender refunded";

            return nrc.FailedPickupAttempts == 0
                ? state
                : $"{state} · {nrc.FailedPickupAttempts} wrong code"
                  + (nrc.FailedPickupAttempts == 1 ? string.Empty : "s");
        }
    }

    // ===== Interbank transfer =====

    public bool HasInterbankTransfer =>
        Transaction.InterbankTransfer is not null;

    public string BeneficiaryText =>
        Transaction.InterbankTransfer is { } bank
            ? $"{bank.BeneficiaryName} · {bank.DestinationAccountNo} at {bank.OtherBankName}"
            : string.Empty;

    public string GatewayText =>
        Transaction.InterbankTransfer is { } bank
            ? $"{bank.GatewayStatus}{ReferenceSuffix(bank.GatewayReference)}"
            : string.Empty;

    public string SettlementText =>
        TransactionDisplay.OrDash(
            Transaction.InterbankTransfer?.SettlementReference);

    private static string FormatUser(
        long userId,
        string? username,
        string? fullName)
    {
        if (!string.IsNullOrWhiteSpace(fullName) &&
            !string.IsNullOrWhiteSpace(username))
        {
            return $"{fullName} ({username})";
        }

        if (!string.IsNullOrWhiteSpace(fullName))
        {
            return fullName;
        }

        if (!string.IsNullOrWhiteSpace(username))
        {
            return username;
        }

        return $"User #{userId}";
    }

    private static string PhoneSuffix(string? phone)
    {
        return string.IsNullOrWhiteSpace(phone)
            ? string.Empty
            : $" · {phone}";
    }

    private static string ReferenceSuffix(string? reference)
    {
        return string.IsNullOrWhiteSpace(reference)
            ? string.Empty
            : $" · ref {reference}";
    }
}