###
GET http://localhost:5121/api/accounts
Accept: application/json

###
POST http://localhost:5121/api/accounts
Content-Type: application/json

{
    "Name": "John Doe",
    "Type": 1,
    "OpeningBalance": 1000.00
}

###
GET http://localhost:5121/api/accounting/gl-accounts
Accept: application/json

###
GET http://localhost:5121/api/accounting/gl-accounts/1
Accept: application/json

###
GET http://localhost:5121/api/accounting/daily-summaries?date=2026-09-21
Accept: application/json

###
GET http://localhost:5121/api/accounting/daily-summaries?date=2026-09-21&glAccountId=1
Accept: application/json

###
GET http://localhost:5121/api/accounting/monthly-summaries?year=2026&month=9
Accept: application/json

###
GET http://localhost:5121/api/accounting/monthly-summaries?year=2026&month=9&glAccountId=1
Accept: application/json

###
GET http://localhost:5121/api/accounting/monthly-summaries?year=2026&month=13
Accept: application/json

###
GET http://localhost:5121/api/audit/logs
Accept: application/json

###
GET http://localhost:5121/api/audit/logs/15
Accept: application/json

###
POST http://localhost:5121/api/dev/audit-test-data/balanced
Accept: application/json

###
POST http://localhost:5121/api/audit/end-of-day?date=2026-09-25
Accept: application/json

###
POST http://localhost:5121/api/dev/audit-test-data/unbalanced

###
POST http://localhost:5121/api/dev/audit-test-data/gl-accounts
Accept: application/json